### ISSUE TITLE
It shows the error message//

### ISSUE THREAD

**Issue by ttlover201212** [eti1/pymdt#2]
File "C:\Users\Administrator\Desktop\decompile\pymdt.py", line 305
SyntaxError: Non-ASCII character '\xc2' in file C:\Users\Administrator\Desktop\d
ecompile\02Gmodem\pymdt.py on line 305, but no encoding declared; see http://pyt
hon.org/dev/peps/pep-0263/ for details

**Comment by eti1** [comment]
Indeed, there was an invisible character on this line, last commit fixed it.
This was not causing trouble with python3.
It should now work ok with the examples from the readme.
